version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.3
    - 5.27.2
    - 5.31.0
    - 5.31.1
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: ts-loader
    versions:
    - 9.0.2
    - 9.1.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.3.0
  - dependency-name: typescript
    versions:
    - 4.1.4
